INSERT INTO ASSETS(SIZE,USABLE_SIZE,CUSTOMER_ID,ASSET_NAME) VALUES (100000,100000,1,'TRY');
INSERT INTO ASSETS(SIZE,USABLE_SIZE,CUSTOMER_ID,ASSET_NAME) VALUES (100,100,2,'DOGE');
INSERT INTO ASSETS(SIZE,USABLE_SIZE,CUSTOMER_ID,ASSET_NAME) VALUES (30,30,2,'BTC');